import { PROMPT_API_URL } from "../../lib/constants.js";

export function renderDisclaimerModal(container, onAccept, onDecline) {
  const overlay = document.createElement("div");
  overlay.className = "modal-overlay";
  overlay.innerHTML = `
    <div class="modal disclaimer-modal">
      <h2>Welcome to Gemini Nano Chat</h2>

      <h3>Hardware Requirements</h3>
      <ul>
        <li><strong>OS:</strong> Windows 10/11, macOS 13+, Linux, ChromeOS (Chromebook Plus)</li>
        <li><strong>Storage:</strong> At least 22 GB free space</li>
        <li><strong>GPU:</strong> &gt;4 GB VRAM, <strong>OR</strong></li>
        <li><strong>CPU:</strong> 16 GB RAM + 4+ cores</li>
        <li><strong>Network:</strong> Unmetered connection (for initial model download only)</li>
      </ul>

      <h3>Important Notices</h3>
      <ul>
        <li>Before using this extension, you must acknowledge <a href="https://policies.google.com/terms/generative-ai/use-policy" target="_blank">Google's Generative AI Prohibited Uses Policy</a>.</li>
        <li>Responses are generated by a local AI model (<strong>Gemini Nano</strong>) and may contain inaccuracies or mistakes.</li>
        <li>Always verify important information from authoritative sources.</li>
        <li>This extension is provided <strong>as-is</strong> with no warranty of any kind. The developers assume no responsibility for the accuracy, completeness, or usefulness of AI-generated content.</li>
        <li>No data is sent to external servers — all processing happens locally on your device.</li>
      </ul>

      <p>
        For more information, see the
        <a href="${PROMPT_API_URL}" target="_blank">Prompt API documentation</a>.
      </p>

      <div class="modal-actions">
        <button id="disclaimer-decline" class="btn btn-secondary">Decline</button>
        <button id="disclaimer-accept" class="btn btn-primary">I Understand — Continue</button>
      </div>
    </div>
  `;

  overlay.querySelector("#disclaimer-accept").addEventListener("click", () => {
    overlay.remove();
    onAccept();
  });

  overlay.querySelector("#disclaimer-decline").addEventListener("click", () => {
    onDecline();
  });

  container.appendChild(overlay);
}
